// 目前只写入已经有来源的祖源线索；未核实的姓名、年代和世系不擅自补写。
export const familyProfile = {
  title: '曹氏家谱',
  shortTitle: '曹氏',
  subtitle: '山西朔州应县 · 小石口',
  origin: '山西省朔州市应县南河种镇小石口村',
  originStatus: '手绘世系图已归档；始迁祖、完整房支与字面仍待核',
  lastUpdated: '2026-08-14',
  completeness: 12,
  sources: [
    {
      label: '家族提供的祖籍线索',
      detail: '“山西朔州应县小石口”',
      state: '待家人确认',
    },
    {
      label: '公开地名资料',
      detail: '小石口村隶属应县南河种镇',
      state: '已记录',
      url: 'https://www.xzqh.org/html/show/sx/25294.html',
    },
  ],
}

export const initialPeople = [
  {
    id: 'cao-tongxiu',
    name: '曹同休',
    generation: 0,
    branch: '手绘图主线',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '姓名与曹建列的上方连线来自第二张放大图，字形和父子关系待家人复核。',
    parentIds: [],
  },
  {
    id: 'cao-jianlie',
    name: '曹建列',
    generation: 1,
    branch: '手绘图主线',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '姓名与曹立中的父子连线来自手绘世系图，年代、籍贯和是否为小石口始迁祖待家人核对。',
    parentIds: ['cao-tongxiu'],
  },
  {
    id: 'cao-lizhong',
    name: '曹立中',
    generation: 2,
    branch: '立中房',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '手绘图中位于曹建列下方的主节点。',
    parentIds: ['cao-jianlie'],
  },
  ...[
    ['cao-yushan', '曹裕善'],
    ['cao-haoshan', '曹好善'],
    ['cao-wangshan', '曹王善'],
    ['cao-bingshan', '曹秉善'],
  ].map(([id, name]) => ({
    id,
    name,
    generation: 3,
    branch: '立中房',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '姓名和与曹立中的分支关系来自手绘世系图，字形及生平信息待家人核对。',
    parentIds: ['cao-lizhong'],
  })),
  {
    id: 'cao-baozhong',
    name: '曹宝中',
    generation: 2,
    branch: '建列房',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '第二张放大图中位于曹建列下方的主节点，字形和连线待家人复核。',
    parentIds: ['cao-jianlie'],
  },
  ...[
    ['cao-fushan', '曹福善'],
    ['cao-wanshan', '曹万善'],
    ['cao-rongshan', '曹荣善'],
    ['cao-lianshan', '曹连善'],
  ].map(([id, name]) => ({
    id,
    name,
    generation: 3,
    branch: '宝中房',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '姓名和与曹宝中的分支关系来自第二张放大图，字形待家人复核。',
    parentIds: ['cao-baozhong'],
  })),
  ...[
    ['cao-jiuzhong', '曹九重', 'cao-yushan'],
    ['cao-jiuxu-shu', '曹九续', 'cao-yushan'],
    ['cao-jiugong', '曹九工', 'cao-haoshan'],
    ['cao-jiuguan', '曹九官', 'cao-wangshan'],
    ['cao-jiuyin', '曹九银', 'cao-wangshan'],
    ['cao-jiucheng', '曹九城', 'cao-wangshan'],
  ].map(([id, name, parentId]) => ({
    id,
    name,
    generation: 4,
    branch: '九字辈·待核',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '姓名和父子连线来自第一张放大图，字形及归属房支待家人复核。',
    parentIds: [parentId],
  })),
  ...[
    ['cao-jiujiang', '曹九江', 'cao-bingshan'],
    ['cao-jiuxu', '曹九旭', 'cao-bingshan'],
    ['cao-jiuzhou', '曹九州', 'cao-fushan'],
    ['cao-jiushuai', '曹九帅', 'cao-fushan'],
    ['cao-jiuda', '曹九达', 'cao-fushan'],
    ['cao-jiuguo', '曹九国', 'cao-wanshan'],
    ['cao-jiuju', '曹九居', 'cao-wanshan'],
    ['cao-jiuceng', '曹九曾', 'cao-rongshan'],
    ['cao-jiuquan', '曹九全', 'cao-rongshan'],
    ['cao-jiuyou', '曹九有', 'cao-lianshan'],
    ['cao-jiuwu', '曹九梧', 'cao-lianshan'],
  ].map(([id, name, parentId]) => ({
    id,
    name,
    generation: 4,
    branch: '九字辈·待核',
    gender: '男',
    years: '待考',
    location: familyProfile.origin,
    status: '待确认',
    note: '姓名和父子连线来自第二、三张放大图，字形及归属房支待家人复核。',
    parentIds: [parentId],
  })),
]

export const sourceMaterials = [
  { id: 'm1', title: '手绘曹氏世系图（原图）', type: '家族原始资料', date: '2026-08-14', state: '图像初录', icon: '▧', asset: '/materials/xiaoshikou-handwritten-tree.jpg' },
]
